# Limpiando data JSON de spotify

## Librerias

In [1]:
#librerias 
from pathlib import Path
import json

import pandas as pd
import numpy as np

## Parsear los JSON

In [3]:
#Definiendo los paths
RAW_SPOTIFY_PATH = Path("/Users/user27/Library/CloudStorage/OneDrive-WPPCloud/Documents/music-letterboxd-eda/data/raw/spotify")
PROCESSED_PATH = Path("/Users/user27/Library/CloudStorage/OneDrive-WPPCloud/Documents/music-letterboxd-eda/data/processed/spotify")

PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

In [4]:
json_files = sorted(RAW_SPOTIFY_PATH.glob("*.json"))

print(f"Total JSON files found: {len(json_files)}")
for file in json_files:
    print(file.name)

Total JSON files found: 18
Streaming_History_Audio_2017-2018_0.json
Streaming_History_Audio_2018-2019_1.json
Streaming_History_Audio_2019-2020_3.json
Streaming_History_Audio_2019_2.json
Streaming_History_Audio_2020-2021_6.json
Streaming_History_Audio_2020_4.json
Streaming_History_Audio_2020_5.json
Streaming_History_Audio_2021-2022_9.json
Streaming_History_Audio_2021_7.json
Streaming_History_Audio_2021_8.json
Streaming_History_Audio_2022-2023_11.json
Streaming_History_Audio_2022_10.json
Streaming_History_Audio_2023-2024_14.json
Streaming_History_Audio_2023_12.json
Streaming_History_Audio_2023_13.json
Streaming_History_Audio_2024-2025_15.json
Streaming_History_Audio_2025-2026_16.json
Streaming_History_Video_2017-2026.json

In [5]:
dfs = []

for file in json_files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    df_temp = pd.DataFrame(data)
    df_temp["source_file"] = file.name
    df_temp["source_type"] = "video" if "Video" in file.name else "audio"
    
    dfs.append(df_temp)

spotify_raw = pd.concat(dfs, ignore_index=True)

/var/folders/gh/ylyhv5j170x1ctr9ry0hqwwm0000gp/T/ipykernel_38222/3045354633.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  spotify_raw = pd.concat(dfs, ignore_index=True)

In [6]:
print(f"Shape: {spotify_raw.shape}")
spotify_raw.head()

Shape: (267011, 25)

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,source_file,source_type
0,2017-10-06T03:10:49Z,"Android-tablet OS 4.4.2 API 19 (Sony, D2305)",5749,GT,138.94.254.183,Shape of You,Ed Sheeran,÷,spotify:track:7qiZfU4dY1lWllzX7mPBI3,None,...,None,clickrow,endplay,False,True,False,NaN,False,Streaming_History_Audio_2017-2018_0.json,audio
1,2017-10-06T03:11:09Z,"Android-tablet OS 4.4.2 API 19 (Sony, D2305)",20728,GT,138.94.254.183,Shape of You,Ed Sheeran,Shape of You,spotify:track:0FE9t6xYkqWXU2ahLh6D8X,None,...,None,clickrow,endplay,False,True,False,NaN,False,Streaming_History_Audio_2017-2018_0.json,audio
2,2017-10-06T03:12:04Z,"Android-tablet OS 4.4.2 API 19 (Sony, D2305)",55567,GT,138.94.254.183,Maps,Maroon 5,V - Deluxe,spotify:track:5rwdhliMmo0aAQ08vU0AOZ,None,...,None,clickrow,endplay,False,True,False,NaN,False,Streaming_History_Audio_2017-2018_0.json,audio
3,2017-10-06T03:12:08Z,"Android-tablet OS 4.4.2 API 19 (Sony, D2305)",5308,GT,138.94.254.183,Holding on to You,Twenty One Pilots,Vessel,spotify:track:3C3cr2JQwXIhqAHqOardVO,None,...,None,clickrow,endplay,False,True,False,NaN,False,Streaming_History_Audio_2017-2018_0.json,audio
4,2017-10-06T03:12:13Z,"Android-tablet OS 4.4.2 API 19 (Sony, D2305)",6302,GT,138.94.254.183,Holding on to You,Twenty One Pilots,Vessel,spotify:track:3C3cr2JQwXIhqAHqOardVO,None,...,None,clickrow,endplay,False,True,False,NaN,False,Streaming_History_Audio_2017-2018_0.json,audio

In [7]:
spotify_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267011 entries, 0 to 267010
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ts                                 267011 non-null  object
 1   platform                           267011 non-null  object
 2   ms_played                          267011 non-null  int64
 3   conn_country                       267011 non-null  object
 4   ip_addr                            267011 non-null  object
 5   master_metadata_track_name         266792 non-null  object
 6   master_metadata_album_artist_name  266792 non-null  object
 7   master_metadata_album_album_name   266792 non-null  object
 8   spotify_track_uri                  266792 non-null  object
 9   episode_name                       218 non-null     object
 10  episode_show_name                  218 non-null     object
 11  spotify_episode_uri                218 non-null     object
 12  audiobook_title                    0 non-null       object
 13  audiobook_uri                      0 non-null       object
 14  audiobook_chapter_uri              0 non-null       object
 15  audiobook_chapter_title            0 non-null       object
 16  reason_start                       267011 non-null  object
 17  reason_end                         267011 non-null  object
 18  shuffle                            267011 non-null  bool
 19  skipped                            267011 non-null  bool
 20  offline                            266955 non-null  object
 21  offline_timestamp                  84698 non-null   float64
 22  incognito_mode                     267011 non-null  bool
 23  source_file                        267011 non-null  object
 24  source_type                        267011 non-null  object
dtypes: bool(3), float64(1), int64(1), object(20)
memory usage: 45.6+ MB

In [8]:
file_summary = (
    spotify_raw
    .groupby(["source_file", "source_type"])
    .size()
    .reset_index(name="rows")
    .sort_values("source_file")
)

file_summary

                                  source_file source_type   rows
0    Streaming_History_Audio_2017-2018_0.json       audio  15486
1    Streaming_History_Audio_2018-2019_1.json       audio  15452
2    Streaming_History_Audio_2019-2020_3.json       audio  15409
3         Streaming_History_Audio_2019_2.json       audio  15296
4    Streaming_History_Audio_2020-2021_6.json       audio  15632
5         Streaming_History_Audio_2020_4.json       audio  15694
6         Streaming_History_Audio_2020_5.json       audio  15633
7    Streaming_History_Audio_2021-2022_9.json       audio  15574
8         Streaming_History_Audio_2021_7.json       audio  15676
9         Streaming_History_Audio_2021_8.json       audio  15644
10  Streaming_History_Audio_2022-2023_11.json       audio  15943
11       Streaming_History_Audio_2022_10.json       audio  15518
12  Streaming_History_Audio_2023-2024_14.json       audio  16078
13       Streaming_History_Audio_2023_12.json       audio  16226
14       Streaming_History_Audio_2023_13.json       audio  16193
15  Streaming_History_Audio_2024-2025_15.json       audio  15923
16  Streaming_History_Audio_2025-2026_16.json       audio  15091
17     Streaming_History_Video_2017-2026.json       video    543

In [9]:
spotify_raw.columns.tolist()

['ts',
 'platform',
 'ms_played',
 'conn_country',
 'ip_addr',
 'master_metadata_track_name',
 'master_metadata_album_artist_name',
 'master_metadata_album_album_name',
 'spotify_track_uri',
 'episode_name',
 'episode_show_name',
 'spotify_episode_uri',
 'audiobook_title',
 'audiobook_uri',
 'audiobook_chapter_uri',
 'audiobook_chapter_title',
 'reason_start',
 'reason_end',
 'shuffle',
 'skipped',
 'offline',
 'offline_timestamp',
 'incognito_mode',
 'source_file',
 'source_type']

# Limpiar el dataset

In [10]:
spotify_clean = spotify_raw.copy()

In [11]:
spotify_clean["ts"] = pd.to_datetime(spotify_clean["ts"], utc=True, errors="coerce")

spotify_clean["ms_played"] = pd.to_numeric(spotify_clean["ms_played"], errors="coerce")

spotify_clean["offline_timestamp"] = pd.to_datetime(
    spotify_clean["offline_timestamp"],
    unit="ms",
    utc=True,
    errors="coerce"
)

In [12]:
spotify_clean["offline"].value_counts(dropna=False)

offline
False    263232
True       3723
None         56
Name: count, dtype: int64

In [13]:
spotify_clean["offline"] = spotify_clean["offline"].fillna(False).astype(bool)

/var/folders/gh/ylyhv5j170x1ctr9ry0hqwwm0000gp/T/ipykernel_38222/1788116610.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  spotify_clean["offline"] = spotify_clean["offline"].fillna(False).astype(bool)

In [14]:
spotify_clean["date"] = spotify_clean["ts"].dt.date
spotify_clean["year"] = spotify_clean["ts"].dt.year
spotify_clean["month"] = spotify_clean["ts"].dt.month
spotify_clean["day"] = spotify_clean["ts"].dt.day
spotify_clean["hour"] = spotify_clean["ts"].dt.hour
spotify_clean["weekday"] = spotify_clean["ts"].dt.day_name()

spotify_clean["minutes_played"] = spotify_clean["ms_played"] / 60000
spotify_clean["hours_played"] = spotify_clean["ms_played"] / 3600000

In [15]:
spotify_clean["content_type"] = np.select(
    [
        spotify_clean["spotify_track_uri"].notna() | spotify_clean["master_metadata_track_name"].notna(),
        spotify_clean["spotify_episode_uri"].notna() | spotify_clean["episode_name"].notna(),
        spotify_clean["audiobook_uri"].notna() | spotify_clean["audiobook_title"].notna(),
        spotify_clean["source_type"].eq("video")
    ],
    [
        "track",
        "episode",
        "audiobook",
        "video"
    ],
    default="unknown"
)

In [16]:
spotify_clean["is_valid_stream"] = spotify_clean["ms_played"] >= 30000
spotify_clean["is_short_stream"] = spotify_clean["ms_played"] < 30000
spotify_clean["is_very_short_stream"] = spotify_clean["ms_played"] < 10000
spotify_clean["is_skipped_custom"] = spotify_clean["skipped"] | (spotify_clean["ms_played"] < 10000)

In [17]:
spotify_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267011 entries, 0 to 267010
Data columns (total 38 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ts                                 267011 non-null  datetime64[ns, UTC]
 1   platform                           267011 non-null  object
 2   ms_played                          267011 non-null  int64
 3   conn_country                       267011 non-null  object
 4   ip_addr                            267011 non-null  object
 5   master_metadata_track_name         266792 non-null  object
 6   master_metadata_album_artist_name  266792 non-null  object
 7   master_metadata_album_album_name   266792 non-null  object
 8   spotify_track_uri                  266792 non-null  object
 9   episode_name                       218 non-null     object
 10  episode_show_name                  218 non-null     object
 11  spotify_episode_uri                218 non-null     object
 12  audiobook_title                    0 non-null       object
 13  audiobook_uri                      0 non-null       object
 14  audiobook_chapter_uri              0 non-null       object
 15  audiobook_chapter_title            0 non-null       object
 16  reason_start                       267011 non-null  object
 17  reason_end                         267011 non-null  object
 18  shuffle                            267011 non-null  bool
 19  skipped                            267011 non-null  bool
 20  offline                            267011 non-null  bool
 21  offline_timestamp                  84698 non-null   datetime64[ns, UTC]
 22  incognito_mode                     267011 non-null  bool
 23  source_file                        267011 non-null  object
 24  source_type                        267011 non-null  object
 25  date                               267011 non-null  object
 26  year                               267011 non-null  int32
 27  month                              267011 non-null  int32
 28  day                                267011 non-null  int32
 29  hour                               267011 non-null  int32
 30  weekday                            267011 non-null  object
 31  minutes_played                     267011 non-null  float64
 32  hours_played                       267011 non-null  float64
 33  content_type                       267011 non-null  object
 34  is_valid_stream                    267011 non-null  bool
 35  is_short_stream                    267011 non-null  bool
 36  is_very_short_stream               267011 non-null  bool
 37  is_skipped_custom                  267011 non-null  bool
dtypes: bool(8), datetime64[ns, UTC](2), float64(2), int32(4), int64(1), object(21)
memory usage: 59.1+ MB

In [18]:
spotify_clean[[
    "ts",
    "offline_timestamp",
    "ms_played",
    "minutes_played",
    "content_type",
    "offline"
]].head()

,ts,offline_timestamp,ms_played,minutes_played,content_type,offline
0,2017-10-06 03:10:49+00:00,NaT,5749,0.095817,track,False
1,2017-10-06 03:11:09+00:00,NaT,20728,0.345467,track,False
2,2017-10-06 03:12:04+00:00,NaT,55567,0.926117,track,False
3,2017-10-06 03:12:08+00:00,NaT,5308,0.088467,track,False
4,2017-10-06 03:12:13+00:00,NaT,6302,0.105033,track,False

In [19]:
spotify_clean["content_type"].value_counts(dropna=False)

content_type
track      266792
episode       218
unknown         1
Name: count, dtype: int64

In [20]:
spotify_clean[["source_type", "content_type"]].value_counts()

source_type  content_type
audio        track           266349
video        track              443
audio        episode            118
video        episode            100
audio        unknown              1
Name: count, dtype: int64

In [21]:
spotify_clean["offline"].value_counts(dropna=False)

offline
False    263288
True       3723
Name: count, dtype: int64

In [22]:
spotify_clean[spotify_clean["content_type"] == "unknown"]

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,day,hour,weekday,minutes_played,hours_played,content_type,is_valid_stream,is_short_stream,is_very_short_stream,is_skipped_custom
250941,2025-06-18 21:06:48+00:00,ios,1626,GT,138.94.254.181,None,None,None,None,None,...,18,21,Wednesday,0.0271,0.000452,unknown,False,True,True,True

In [23]:
cols_all_null = [col for col in spotify_clean.columns if spotify_clean[col].isna().all()]

cols_all_null

['audiobook_title',
 'audiobook_uri',
 'audiobook_chapter_uri',
 'audiobook_chapter_title']

In [24]:
spotify_clean = spotify_clean.drop(columns=cols_all_null)

In [25]:
ordered_cols = [
    # tiempo
    "ts", "date", "year", "month", "day", "hour", "weekday",
    
    # identificadores
    "spotify_track_uri", "spotify_episode_uri",
    
    # metadata
    "master_metadata_track_name",
    "master_metadata_album_artist_name",
    "master_metadata_album_album_name",
    "episode_name",
    "episode_show_name",
    
    # consumo
    "ms_played", "minutes_played", "hours_played",
    
    # flags
    "skipped", "is_valid_stream", "is_short_stream", "is_very_short_stream", "is_skipped_custom",
    
    # contexto
    "platform", "conn_country", "reason_start", "reason_end", "shuffle", "offline", "incognito_mode",
    
    # clasificación
    "content_type", "source_type",
    
    # técnico
    "source_file", "offline_timestamp"
]

In [26]:
spotify_clean = spotify_clean[[col for col in ordered_cols if col in spotify_clean.columns]]

In [27]:
spotify_clean.duplicated().sum()

np.int64(418)

In [28]:
spotify_clean = spotify_clean.drop_duplicates()

In [29]:
print(spotify_clean.shape)
spotify_clean.info()

(266593, 33)
<class 'pandas.core.frame.DataFrame'>
Index: 266593 entries, 0 to 267010
Data columns (total 33 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ts                                 266593 non-null  datetime64[ns, UTC]
 1   date                               266593 non-null  object
 2   year                               266593 non-null  int32
 3   month                              266593 non-null  int32
 4   day                                266593 non-null  int32
 5   hour                               266593 non-null  int32
 6   weekday                            266593 non-null  object
 7   spotify_track_uri                  266374 non-null  object
 8   spotify_episode_uri                218 non-null     object
 9   master_metadata_track_name         266374 non-null  object
 10  master_metadata_album_artist_name  266374 non-null  object
 11  master_metadata_album_album_name   266374 non-null  object
 12  episode_name                       218 non-null     object
 13  episode_show_name                  218 non-null     object
 14  ms_played                          266593 non-null  int64
 15  minutes_played                     266593 non-null  float64
 16  hours_played                       266593 non-null  float64
 17  skipped                            266593 non-null  bool
 18  is_valid_stream                    266593 non-null  bool
 19  is_short_stream                    266593 non-null  bool
 20  is_very_short_stream               266593 non-null  bool
 21  is_skipped_custom                  266593 non-null  bool
 22  platform                           266593 non-null  object
 23  conn_country                       266593 non-null  object
 24  reason_start                       266593 non-null  object
 25  reason_end                         266593 non-null  object
 26  shuffle                            266593 non-null  bool
 27  offline                            266593 non-null  bool
 28  incognito_mode                     266593 non-null  bool
 29  content_type                       266593 non-null  object
 30  source_type                        266593 non-null  object
 31  source_file                        266593 non-null  object
 32  offline_timestamp                  84674 non-null   datetime64[ns, UTC]
dtypes: bool(8), datetime64[ns, UTC](2), float64(2), int32(4), int64(1), object(16)
memory usage: 50.8+ MB

In [30]:
spotify_clean.to_parquet(
    "/Users/user27/Library/CloudStorage/OneDrive-WPPCloud/Documents/music-letterboxd-eda/data/processed/spotify/spotify_all_clean.parquet",
    index=False
)

In [31]:
spotify_tracks = spotify_clean[spotify_clean["content_type"] == "track"]
spotify_episodes = spotify_clean[spotify_clean["content_type"] == "episode"]

In [32]:
spotify_tracks.to_parquet("/Users/user27/Library/CloudStorage/OneDrive-WPPCloud/Documents/music-letterboxd-eda/data/processed/spotify/spotify_tracks_clean.parquet", index=False)
spotify_episodes.to_parquet("/Users/user27/Library/CloudStorage/OneDrive-WPPCloud/Documents/music-letterboxd-eda/data/processed/spotify/spotify_episodes_clean.parquet", index=False)

In [34]:
print("Shape:", spotify_clean.shape)

Shape: (266593, 33)

In [35]:
spotify_clean["content_type"].value_counts()

content_type
track      266374
episode       218
unknown         1
Name: count, dtype: int64

In [36]:
spotify_clean["year"].value_counts().sort_index()

year
2017      636
2018    23397
2019    31793
2020    39877
2021    52634
2022    37421
2023    33511
2024    19168
2025    24376
2026     3780
Name: count, dtype: int64

In [37]:
spotify_clean["minutes_played"].describe()

count    266593.000000
mean          2.081433
std           2.083877
min           0.000000
25%           0.084250
50%           1.828567
75%           3.557200
max          70.133150
Name: minutes_played, dtype: float64

In [38]:
spotify_tracks.shape, spotify_episodes.shape

((266374, 33), (218, 33))

In [39]:
spotify_clean["ts"].min(), spotify_clean["ts"].max()

(Timestamp('2017-10-06 03:10:49+0000', tz='UTC'),
 Timestamp('2026-03-15 19:55:03+0000', tz='UTC'))